x-db-env: &db-env
  DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/subtrack}

services:
  db:
    profiles: ["localdb"]
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subtrack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - subtrack

  migrate:
    depends_on:
      db:
        condition: service_healthy
        required: false
    profiles: ["migrate"]
    build:
      context: .
      dockerfile: Dockerfile
      target: prisma
    command: "bun run db:migrate:deploy"
    env_file:
      - path: ./apps/api/.env
        required: false
    environment:
      <<: *db-env
    networks:
      - subtrack

  seed:
    depends_on:
      migrate:
        condition: service_completed_successfully
        required: false
      db:
        condition: service_healthy
        required: false
    profiles: ["seed"]
    build:
      context: .
      dockerfile: Dockerfile
      target: prisma
    command: "bun run db:seed"
    env_file:
      - path: ./apps/api/.env
        required: false
    environment:
      <<: *db-env
    networks:
      - subtrack

  api:
    depends_on:
      db:
        condition: service_healthy
        required: false
      seed:
        condition: service_completed_successfully
        required: false
      migrate:
        condition: service_completed_successfully
        required: false
    build:
      context: .
      dockerfile: Dockerfile
      target: api-runner
    restart: unless-stopped
    ports:
      - ${PORT:-8080}:8080
    env_file:
      - path: ./apps/api/.env
        required: false
    environment:
      PORT: 8080
      <<: *db-env
    healthcheck:
      test: ["CMD-SHELL", "bun dist/healthy.js"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - subtrack

  web:
    depends_on:
      api:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: web-runner
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - path: ./apps/web/.env
        required: false
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://api:8080
    networks:
      - subtrack

volumes:
  postgres_data: null
networks:
  subtrack:
    driver: bridge
